// src/pages/Home.tsx
import Article from "../components/Article";
import { useRegulations } from "../providers/RegulationsProvider/RegulationsContext";

function Home() {
  const { regulationsAndGuidelines } = useRegulations();

  return (
    <section id="home">
      <div className="container">
        <table className="table" style={{ width: "100%" }}>
          <tbody>
            {regulationsAndGuidelines.labels.map((label) => (
              <tr key={label.type}>
                <td>{label.type}</td>
                <td>{label.description}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <h2 className="title">
          <a className="anchor" id="contents" href="./#contents">
            Contents
          </a>
        </h2>

        <ul>
          {regulationsAndGuidelines.articles.map((article) => (
            <li key={article.id}>
              Article {article.id}:{" "}
              <a href={`#article-${article.id}-${article.name}`}>
                {article.description.split(": ")[1]}
              </a>
            </li>
          ))}
        </ul>

        <hr />

        {regulationsAndGuidelines.articles.map((article) => (
          <Article key={article.id} article={article} />
        ))}
      </div>
    </section>
  );
}

export default Home;

// src/pages/Home.vue
<template>
<div id="home">
  <div class="container">
    <table class="table" style="width: 100%;">
      <tr v-for="(label,index) in regulations.labels" :key="index">
        <td>{{label.type}}</td><td>{{label.description}}</td>
      </tr>
    </table>

    <h2 class='title'><a class="anchor" id="contents" href="./#contents">Contents</a></h2>

    <ul>
      <li v-for="(article,index) in regulations.articles" :key="index">
        Article {{article.id}}: <a :href="`article-${article.id}-${article.name}` | link">{{article.description.split(': ')[1]}}</a>
      </li>
    </ul>

    <hr>

    <div class="article" v-for="(article,index) in regulations.articles" :key="index">
      <span class="anchor" :id="article.id"/>
      <span class="anchor" :id="article.name2"/>
      <span class="anchor" :id="`article-${article.id}-${article.name}`"/>
      <h2 class="title article-title">
        <a :href="`article-${article.id}-${article.name}` | link">Article {{article.id}}</a>: {{article.description.split(': ')[1]}}
      </h2>

      <ul>
        <div v-for="(regulation,regIndex) in article.regulations" :key="regIndex" :class="'indent-' + regulation.level">
          <li v-if="regulation.description" class='regulation' :id="regulation.id">
            <span class="anchor" :id="regulation.id"/>
            <div><a class="anchor" :href="regulation.id | link">{{regulation.id}}</a>) {{regulation.description}}</div>
          </li>
          <li v-for="(guideline,regIndex) in regulation.guidelines" :key="regIndex" class='guideline' :id="regulation.id + guideline.pluses">
            <span class="anchor" :id="regulation.id + guideline.pluses"/>
            <div><a :href="(guideline.id + guideline.pluses) | link">{{guideline.id + guideline.pluses}}</a>) <span class="tag">{{guideline.label}}</span> {{guideline.description}}</div>
          </li>
        </div>
      </ul>
    </div>
  </div>
</div>
</template>

<script>
export default {
  name: 'Main',
  data () {
    return {
      regulations: this.$root.$data.regulations
    }
  }
}
</script>

<style>

</style>
