// src/App.jsx
import { useState } from "react";
import {
  BrowserRouter as Router,
  Switch,
  Route,
  Link,
  Redirect,
  useHistory,
} from "react-router-dom";
import Home from "./pages/Home";
import Search from "./pages/Search";
import regulations from "./assets/regulationsAndGuidelines.json";

function Header() {
  const history = useHistory();
  const [query, setQuery] = useState("");

  const search = (e) => {
    e.preventDefault();
    console.log(history);
    history.push(`/search?q=${query}`);
  };

  return (
    <nav className="navbar is-flex" role="navigation">
      <div className="navbar-brand is-inline-flex">
        <Link
          className="navbar-item"
          style={{ display: "block", lineHeight: "1em" }}
          to="/"
        >
          <h1 style={{ margin: "0px" }}>WCA-Regs</h1>
          <span style={{ fontSize: ".65em" }}>
            Version: {regulations.version}
          </span>
        </Link>
      </div>
      <div className="navbar-item field is-inline-flex stretch">
        <form className="control stretch" onSubmit={search}>
          <input
            className="input"
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />
          <input type="submit" style={{ display: "none" }} />
        </form>
      </div>
    </nav>
  );
}

function App() {
  return (
    <Router>
      <div id="app">
        <Header />
        <main>
          <Switch>
            <Route exact path="/">
              <Home />
            </Route>
            <Route path="/search">
              <Search />
            </Route>
            <Route path="*">
              <Redirect to="/" />
            </Route>
          </Switch>
        </main>
      </div>
    </Router>
  );
}

export default App;

// src/App.vue
<template>
  <div id="app">
    <nav class="navbar is-inline-flex-touch" role="navigation">
      <div class="navbar-brand is-hidden-mobile">
        <router-link class="navbar-item" style="display: block; line-height: 1em" to="/">
          <h1 style="margin: 0px">WCA-Regs</h1>
          <span style="font-size: .65em;">Version: {{this.$root.$data.regulations.version}}</span>
        </router-link>
      </div>
      <div class="navbar-item stretch">
        <div class="control stretch">
          <input class="input" v-model="query" @keyup.13="updateRoute" type="text"/>
        </div>
      </div>
    </nav>

    <keep-alive include="Main" exclude="Search">
      <router-view/>
    </keep-alive>
  </div>
</template>

<script>
// import _ from 'lodash'

export default {
  name: 'app',
  data () {
    return {
      query: this.$route.query.q
    }
  },
  methods: {
    updateRoute () {
      if (this.query) {
        this.$router.push({ name: 'search', query: { q: this.query } })
      } else {
        this.$router.push({ name: 'home' })
      }
    }
  }
}
</script>

<style>

body {
  font-weight: 300;
}

.tag {
  font-weight: 500;
}

.article {
  margin-top: 20px;
}

.article-title {
  margin-top: 20px;
  margin-bottom: 20px;
}

ul li, ol li {
  line-height: 175%;
}

ul {
  margin-left: 2em;
}

.indent-1 {
  margin-left: 0em;
}

.indent-2 {
  margin-left: 2em;
}

.indent-3 {
  margin-left: 4em;
}

.indent-4 {
  margin-left: 8em;
}

:target > div {
  background-color: yellow;
}

:target > div > .tag {
  background-color: rgb(240, 240, 0);
}
</style>
